### ISSUE TITLE
Cache policy

### ISSUE THREAD

**Issue by ronanrodrigo** [ronanrodrigo/Frisbee#9]

**Comment by williamhjcho** [comment]
What do you mean by `cache policy`?
Now that `NetworkGetter` receives a `URLSession`, it should just be up to the framework's user if they want it implemented and how

Or are you thinking about the "default" `URLSession`  created by the factory?

**Comment by ronanrodrigo** [comment]
@william-wc You are right. I was thinking to implement our own cache. But with URLSession injected they can handle this.
